spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/currates
    username: currates
    password: super_secret_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
#  ssl:
#    key-store: classpath:cert.p12
#    key-store-password: DiamondAboba
#    key-store-type: PKCS12
#    key-alias: currates

springdoc:
  swagger-ui:
    path: /swagger.html